/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ilcntioxftiohbxccehl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsY250aW94ZnRpb2hieGNjZWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1Njk1MjAsImV4cCI6MjA4OTE0NTUyMH0.PxF_rID-jSjpYusr3JY5S7o3nJIixx4N5n-pluMnwy0"